//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenueForecast.Common.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OperationalPortalDBEntities : DbContext
    {
        public OperationalPortalDBEntities()
            : base("name=OperationalPortalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<InvoiceMonthly> InvoiceMonthlies { get; set; }
        public virtual DbSet<MSA> MSAs { get; set; }
        public virtual DbSet<PoDetail> PoDetails { get; set; }
        public virtual DbSet<PoHeader> PoHeaders { get; set; }
        public virtual DbSet<PoUtilization> PoUtilizations { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<e> e { get; set; }
        public virtual DbSet<ShiftAllowance> ShiftAllowances { get; set; }
        public virtual DbSet<UsersInRole> UsersInRoles { get; set; }
        public virtual DbSet<WorkingDay> WorkingDays { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<SowDetailActual> SowDetailActuals { get; set; }
        public virtual DbSet<SowHeader> SowHeaders { get; set; }
        public virtual DbSet<EmployeeRole> EmployeeRoles { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<SowDetail> SowDetails { get; set; }
    }
}
