//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenueForecast.Common.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OperationalPortalDBEntities : DbContext
    {
        public OperationalPortalDBEntities()
            : base("name=OperationalPortalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<InvoiceMonthly> InvoiceMonthlies { get; set; }
        public virtual DbSet<MSA> MSAs { get; set; }
        public virtual DbSet<PoDetail> PoDetails { get; set; }
        public virtual DbSet<PoHeader> PoHeaders { get; set; }
        public virtual DbSet<PoUtilization> PoUtilizations { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectEmployee> ProjectEmployees { get; set; }
        public virtual DbSet<ProjectWorkingDay> ProjectWorkingDays { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ShiftAllowance> ShiftAllowances { get; set; }
        public virtual DbSet<SowDetail> SowDetails { get; set; }
        public virtual DbSet<SowDetailActual> SowDetailActuals { get; set; }
        public virtual DbSet<SowHeader> SowHeaders { get; set; }
        public virtual DbSet<SowProject> SowProjects { get; set; }
        public virtual DbSet<UsersInRole> UsersInRoles { get; set; }
    
        public virtual int sp_GenerateInvoice(string sowId, int? month, int? year, string pONo)
        {
            var sowIdParameter = sowId != null ?
                new ObjectParameter("SowId", sowId) :
                new ObjectParameter("SowId", typeof(string));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var pONoParameter = pONo != null ?
                new ObjectParameter("PONo", pONo) :
                new ObjectParameter("PONo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GenerateInvoice", sowIdParameter, monthParameter, yearParameter, pONoParameter);
        }
    }
}
