//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenueForecast.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PoDetail()
        {
            this.PoUtilizations = new HashSet<PoUtilization>();
        }
    
        public long PoDetailsID { get; set; }
        public int PoHeaderID { get; set; }
        public int MileStones { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual PoHeader PoHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PoUtilization> PoUtilizations { get; set; }
    }
}
