//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenueForecast.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectWorkingDay
    {
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
        public string Month { get; set; }
        public Nullable<int> WorkingDays { get; set; }
        public int SowId { get; set; }
    }
}
