//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenueForecast.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftAllowance
    {
        public int ShiftId { get; set; }
        public long Id { get; set; }
        public long Amount { get; set; }
        public int EmpId { get; set; }
        public long ParentId { get; set; }
    
        public virtual ProjectEmployee ProjectEmployee { get; set; }
    }
}
