//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevenueForecast.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SowDetailActual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SowDetailActual()
        {
            this.InvoiceMonthlies = new HashSet<InvoiceMonthly>();
        }
    
        public long Id { get; set; }
        public int SowDetailId { get; set; }
        public int? UtilizationPercentage { get; set; }
        public int? TotalAmount { get; set; }
        public int? NoOfDays { get; set; }
        public int EmpId { get; set; }
        public string Month { get; set; }
        public int? Year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceMonthly> InvoiceMonthlies { get; set; }
        public virtual SowDetail SowDetail { get; set; }
    }
}
